path_to_features_data: "./data.nosync/mwc2022/features/EDA_features_noart_freqfet-3.npz"
path_to_save_data_avgs: "./data.nosync/mwc2022/results/nested_avg_xgboost_25top.h5"
path_to_save_data_all: "./data.nosync/mwc2022/results/nested_all_xgboost_25top.h5"
generator_seeds:
  - 42 
  - 69
  - 420
n_seeds_to_test_classifiers: 5
n_seeds_to_test_folds: 5
n_seeds_to_undersample: 5
n_folds_outer: 5
n_folds_inner: 5

n_jobs: 125
timeout: # seconds
max_resources: 'auto' # max iterations permitted in each hyperparameter search. If empty, it will be set to "auto"
n_candidates: 'exhaust'
debug_mode: False

subset_of_features: 25 # select percentage of features to select
path_to_feature_importance_list_left: "./data.nosync/mwc2022/feature_importance/importance_xgboost_left.csv"
path_to_feature_importance_list_right: "./data.nosync/mwc2022/feature_importance/importance_xgboost_right.csv"