path_to_features_data: "./data.nosync/usilaughs/features/EDA_features_noart_freqfet-3.npz"
path_to_save_data_avgs: "./data.nosync/usilaughs/results/nested_avg_Testmac.h5"
path_to_save_data_all: "./data.nosync/usilaughs/results/nested_all_Testmac.h5"
generator_seeds:
  - 42 
  - 69
  - 420
n_seeds_to_test_classifiers: 2
n_seeds_to_test_folds: 2
n_seeds_to_undersample: 2
n_folds_outer: 5
n_folds_inner: 5

n_jobs: 8
timeout: 1 # seconds
max_resources: 100 # max iterations permitted in each hyperparameter search. If empty, it will be set to "auto"
debug_mode: False