path_to_features_data: "./data.nosync/mwc2022/features/EDA_features_noart-2.npz"
path_to_save_data_avgs: "./data.nosync/mwc2022/results/n_fold_avg.h5"
path_to_save_data_all: "./data.nosync/mwc2022/results/n_fold_all.h5"
generator_seeds:
  - 42 
  - 69
  - 420
n_seeds_to_test_classifiers: 10
n_seeds_to_test_folds: 10
n_seeds_to_undersample: 10
n_fols: 5

n_jobs: 5