path_to_features_data: "./data.nosync/mwc2022/features/EDA_features_noart_freqfet-3.npz"
path_to_save_data_avgs: "./data.nosync/mwc2022/results/nested_avg_smaller/"
path_to_save_data_all: "./data.nosync/mwc2022/results/nested_all_smaller/"
generator_seeds:
  - 42 
  - 69
  - 420
n_seeds_to_test_classifiers: 5
n_seeds_to_test_folds: 5
n_seeds_to_undersample: 5
n_folds_outer: 5
n_folds_inner: 5

# n_jobs: 8
timeout: # seconds
max_resources: 100 # max iterations permitted in each hyperparameter search. If empty, it will be set to "auto"
n_candidates: "exhaust"
debug_mode: False