path_to_main_folder: "/Users/leonardoalchieri/Datasets/MWC2022_Sleep/sleep_data"
path_to_save_folder: "./data.nosync/mwc2022/filtered_artefact"
# path_to_experiment_time: "./data.nosync/mwc2022/all_experimento_info.csv"
cutoff_frequency: 0.4 # should not be changed, used like this by Elena
butterworth_order: 1 # should not be changed, used like this by Elena
n_jobs: 1 # -1 for "all cores"
plots: True
clean_plots: True
mode: 2
device: "E4"
concat_sessions: True
subset_data: True
artefact_detection: 1 # if 0, no detection. If 1, using Gashi's method. 
artefact_window_size: 600
# If 2, using an ACC-based method. For 2, ACC filtered data is needed.
# acc_data_path: "/Users/leonardoalchieri/Datasets/USILaughs/participants"

