path_to_main_folder: "/Users/leonardoalchieri/Datasets/MWC2022_Sleep/sleep_data"
# path_to_main_folder: "/Users/leonardoalchieri/Datasets/USILaughs/participants"
# path_to_save_folder: "./data.nosync/usilaughs/filtered_standardized_bilateral"
path_to_save_folder: "./data.nosync/mwc2022/filtered_standardized_bilateral"
path_to_experiment_info: "./data.nosync/mwc2022/all_experimento_info.csv" # this is used for MWC2022 to remove the sessions that do not represent a sleep night label
# path_to_experiment_time: "./data.nosync/usilaughs/experiment_time.csv" # mandatory for usilaughs
# acc_data_path: "./data.nosync/usilaughs/filtered/*/ACC/*.parquet"

# accepted values: "standardize", "min_max", "none", "robust_scaling_with_irq", 
# "log_transformation", "yeo_johnson_transformation", "quantile_transformation"
rescaling_method: "standardize" 
cutoff_frequency: 0.4 # should not be changed, used like this by Elena Di Lascio
butterworth_order: 1 # should not be changed, used like this by Elena Di Lascio
n_jobs: -1 # -1 for "all cores"
plots: False
clean_plots: False

mode: 2  # 1 for USIlaughs, 2 for MWC2022
device: "E4"
concat_sessions: True
subset_data: False # this should be used for debugging

artefact_detection: 0 # if 0, no detection. If 1, using Gashi's method. 2 for ACC based method
artefact_window_size: 5 # necessary parameter for artefact_detection 1 only
acc_threshold: # set the thresold for ACC cutoff based for artefact_detection 2 method only

calculate_diff: True # if True, the difference between the left and right side EDA data is calculated. New feature for bilateral fusion