path_to_experiment_info: "./data.nosync/mwc2022/all_experimento_info.csv"
eda_data_base_path: "./data.nosync/mwc2022/filtered/*/EDA/*.parquet"
eda_data_format: "parquet"
path_to_save_file: "./data.nosync/mwc2022/segmented/EDA_test1.json"

mode: 2
segment_size_in_secs: 600 # default should be 4 for usilaughs and 600 for mwc2022
eda_sample_rate: 4
artifacts: False

components:
  - "mixed-EDA"
  - "phasic-EDA"
  # - "tonic-EDA"