path_to_segmented_data: "./data.nosync/usilaughs/segmented/EDA_segmented_noart-3.npz"
artifacts: False 
path_to_save_file: "./data.nosync/usilaughs/features/EDA_features_noart_freqfet-3.npz"

n_jobs: -1