path_to_segmented_data: "./data.nosync/mwc2022/segmented/EDA_segmented_noart_bilateral_fusion.npz"
artifacts: False 
path_to_save_file: "./data.nosync/mwc2022/features/EDA_features_noart_bilateral_fusion.npz"

bilateral_fusion: True

n_jobs: 9