path_to_experiment_info: "./data.nosync/usilaughs/all_experimento_info.csv"
eda_data_base_path: "./data.nosync/usilaughs/filtered_complete_cut/*/EDA/*.parquet"
eda_data_format: "parquet"
path_to_save_file: "./data.nosync/usilaughs/segmented/EDA_segmented_noart-2.npz"

mode: 1 # 1 for usilaughs, 2 for mwc2022
segment_size_in_secs: 4 # default should be 4 for usilaughs and 600 for mwc2022
eda_sample_rate: 4
artifacts: False

components:
  - "mixed-EDA"
  - "phasic-EDA"
  - "tonic-EDA"

users_to_remove:
  - "s092"
  - "s089"