path_to_features_data: "./data.nosync/usilaughs/features/EDA_features_noart_freqfet-3.npz"
path_to_save_data: "./data.nosync/usilaughs/results/cliff_delta_complete-freqfet-3.json"
alpha: 0.05
components: #NOTE: the order should match the order inside config_segmentation.yml
  - "mixed-EDA"
  - "phasic-EDA"
  - "tonic-EDA"
n_jobs: 8