path_to_features_data: "./data.nosync/usilaughs/features/EDA_features_noart_bilateral_fusion.npz"
path_to_save_data: "./data.nosync/usilaughs/results/correlation_rl_features_bilateral.json"
alpha: 0.05
components: #NOTE: the order should match the order inside config_segmentation.yml
  - "mixed-EDA"
  - "phasic-EDA"
  - "tonic-EDA"
bilateral: True