path_to_data: "./data.nosync/usilaughs/filtered_complete_cut/*/EDA/*.parquet"
data_format: "parquet"
time_scale: 20
path_to_save_data: "./data.nosync/usilaughs/results/dcca.json" # the format has to be json
detrended: True # if True, the method used will be the Detrended Time-Lagged Cross Correlation Coefficient. Otherwise, it will be a simple Time-Lagged Cross Correlation Coefficient.