path_to_data: "./data.nosync/usilaughs/filtered_complete_cut/*/EDA/*.parquet"
data_format: "parquet"
path_to_save_data: "./data.nosync/usilaughs/results/dtw.json" # the format has to be json
n_jobs: -1
signal_component: "mixed-EDA"